1a:
  product: ALEXI
  version: v1
  parameter: evapotranspiration
  resolution: daily
  variable: ETA
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2005-01-01'
    e: '2005-01-02'
  nodata: -9999
1b:
  product: ALEXI
  version: v1
  parameter: evapotranspiration
  resolution: weekly
  variable: ETA
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2005-01-01'
    e: '2005-01-15'
  nodata: -9999
2a:
  product: ASCAT
  version: v3.1.1
  parameter: soil_water_index
  resolution: daily
  variable: SWI_010
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2007-01-01'
    e: '2007-01-02'
  nodata: -9999
4a:
  product: CHIRPS
  version: v2.0
  parameter: precipitation
  resolution: daily
  variable: PCP
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2007-01-01'
    e: '2007-01-02'
  nodata: -9999
4b:
  product: CHIRPS
  version: v2.0
  parameter: precipitation
  resolution: monthly
  variable: PCP
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2007-01-01'
    e: '2007-01-02'
  nodata: -9999
5a:
  product: CMRSET
  version: v1
  parameter: evapotranspiration
  resolution: monthly
  variable: ETA
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2007-01-01'
    e: '2007-01-31'
  nodata: -9999
6a:
  product: DEM
  version: v1
  parameter: DEM
  resolution: 30s
  variable: af
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: null
    e: null
  nodata: -9999
6b:
  product: DEM
  version: v1
  parameter: DIR
  resolution: 30s
  variable: af
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: null
    e: null
  nodata: -9999
9a:
  product: FEWS
  version: v4
  parameter: evapotranspiration
  resolution: daily
  variable: ETP
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
10a:
  product: GLDAS
  version: v2.1
  parameter: evapotranspiration
  resolution: three_hourly
  variable: ETA
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
10b:
  product: GLDAS
  version: v2.1
  parameter: evapotranspiration
  resolution: monthly
  variable: ETA
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
11a:
  product: GLEAM
  version: v3.3a
  parameter: evapotranspiration
  resolution: daily
  variable: ETA
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
11b:
  product: GLEAM
  version: v3.3a
  parameter: evapotranspiration
  resolution: monthly
  variable: ETA
  bbox:
    w: -180.0
    n: 90.0
    e: 180.0
    s: -90.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
11c:
  product: GLEAM
  version: v3.3b
  parameter: evapotranspiration
  resolution: daily
  variable: ETA
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
11d:
  product: GLEAM
  version: v3.3b
  parameter: evapotranspiration
  resolution: monthly
  variable: ETA
  bbox:
    w: -180.0
    n: 90.0
    e: 180.0
    s: -90.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
12a:
  product: GPM
  version: v6
  parameter: precipitation
  resolution: daily
  variable: PCP
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
12b:
  product: GPM
  version: v6
  parameter: precipitation
  resolution: monthly
  variable: PCP
  bbox:
    w: -180.0
    n: 90.0
    e: 180.0
    s: -90.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
13a:
  product: HiHydroSoil
  version: v1
  parameter: soil
  resolution: 30s
  variable: wcsat_topsoil
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: null
    e: null
  nodata: -9999
14a:
  product: JRC
  version: v1
  parameter: water
  resolution: 1s
  variable: occurrence
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: null
    e: null
  nodata: -9999
15a:
  product: MCD12Q1
  version: v6
  parameter: land
  resolution: yearly
  variable: LC
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-12-31'
  nodata: -9999
15b:
  product: MCD12Q1
  version: v6
  parameter: land
  resolution: yearly
  variable: LU
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-12-31'
  nodata: -9999
16a:
  product: MCD43A3
  version: v6
  parameter: land
  resolution: daily
  variable: AlbedoBSA
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
16b:
  product: MCD43A3
  version: v6
  parameter: land
  resolution: daily
  variable: AlbedoWSA
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
17a:
  product: MOD09GQ
  version: v6
  parameter: land
  resolution: daily
  variable: REFb01
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
17b:
  product: MOD09GQ
  version: v6
  parameter: land
  resolution: daily
  variable: REFb02
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
18a:
  product: MOD10A2
  version: v6
  parameter: land
  resolution: eight_daily
  variable: SnowFrac
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-09'
  nodata: -9999
18b:
  product: MOD10A2
  version: v6
  parameter: land
  resolution: eight_daily
  variable: SnowExt
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-09'
  nodata: -9999
19a:
  product: MOD11A2
  version: v6
  parameter: land
  resolution: eight_daily
  variable: LSTday
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-09'
  nodata: -9999
19b:
  product: MOD11A2
  version: v6
  parameter: land
  resolution: eight_daily
  variable: LSTnight
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-09'
  nodata: -9999
20a:
  product: MOD13Q1
  version: v6
  parameter: land
  resolution: sixteen_daily
  variable: NDVI
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-17'
  nodata: -9999
21a:
  product: MOD15A2H
  version: v6
  parameter: land
  resolution: eight_daily
  variable: Fpar
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-09'
  nodata: -9999
21b:
  product: MOD15A2H
  version: v6
  parameter: land
  resolution: eight_daily
  variable: Lai
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-09'
  nodata: -9999
22a:
  product: MOD16A2
  version: v6
  parameter: evapotranspiration
  resolution: eight_daily
  variable: ET
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-09'
  nodata: -9999
22b:
  product: MOD16A2
  version: v6
  parameter: evapotranspiration
  resolution: eight_daily
  variable: ETP
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-09'
  nodata: -9999
23a:
  product: MOD17A2H
  version: v6
  parameter: land
  resolution: eight_daily
  variable: GPP
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-09'
  nodata: -9999
24a:
  product: MYD13
  version: v6
  parameter: land
  resolution: sixteen_daily
  variable: NDVI
  bbox:
    w: -5.0
    n: 30.0
    e: 5.0
    s: 25.0
  period:
    s: '2008-01-01'
    e: '2008-01-18'
  nodata: -9999
26a:
  product: RFE
  version: v2
  parameter: precipitation
  resolution: daily
  variable: PCP
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
27a:
  product: SEBS
  version: v1
  parameter: energy
  resolution: monthly
  variable: ETM
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
29a:
  product: TRMM
  version: v7a
  parameter: precipitation
  resolution: monthly
  variable: PCP
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: '2008-01-01'
    e: '2008-01-02'
  nodata: -9999
30a:
  product: TWC
  version: v1
  parameter: water
  resolution: 5m
  variable: WPL
  bbox:
    w: -19.0
    n: 38.0
    e: 55.0
    s: -35.0
  period:
    s: null
    e: null
  nodata: -9999
