# https://github.com/readthedocs/readthedocs.org/blob/master/docs/guides/build-using-too-many-resources.rst#use-pip-when-possible
name: _IHEWAcollect
# channels:
#   - defaults
#   - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - pandas
  - pyyaml
  # - libgdal=3.0.*
  # - gdal=3.0.*
